name: Run Doctor Service Automation

on:
  workflow_dispatch:
    inputs:
      input_json:
        description: 'Input JSON string for Doctor Service automation'
        required: true

jobs:
  run-dr-service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm install
          npx playwright install
      - name: Run dr_service.js
        env:
          INPUT_JSON: ${{ github.event.inputs.input_json }}
        run: node automations/dr_service.js
