name: Run Doctor Data Automation

on:
  workflow_dispatch:  

jobs:
  run-doctor-data:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 📦 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🧪 Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: 🚀 Run doctor_data.js
        run: |
          node automations/hierarchy_data.js
