name: Run MSL Detailed Automation

on:
  workflow_dispatch:
    inputs:
      input_json:
        description: 'Input JSON string for MSL Detailed automation'
        required: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

  setup-node:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

  install-deps:
    needs: setup-node
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📦 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 💾 Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 💾 Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers

      - name: 🧪 Install dependencies
        run: |
          npm ci
          npx playwright install

  run-script:
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📦 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 💾 Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 💾 Restore Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers

      - name: 🚀 Run msl_detailed.js
        env:
          INPUT_JSON: ${{ github.event.inputs.input_json }}
        run: node automations/msl_detailed.js
