name: Playwright Automation

on:
  workflow_dispatch:
    inputs:
      automation:
        description: 'Which automation to run (e.g., msl_detailed or dr_service)'
        required: true
      input_json:
        description: 'Input JSON string to pass to script (months, year, folderId, etc.)'
        required: true

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📦 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🧪 Install dependencies
        run: |
          npm install
          npx playwright install

      - name: 🚀 Run selected Playwright script
        env:
          INPUT_JSON: ${{ toJson(github.event.inputs.input_json) }}
        run: |
          node automations/${{ github.event.inputs.automation }}.js
