name: Playwright Automation

on:
  workflow_dispatch:
    inputs:
      input_json:
        description: 'Input JSON for month, year, and yearIdMap'
        required: true

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📦 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🧪 Install dependencies
        run: |
          npm install
          npx playwright install

      - name: 🚀 Run Playwright script
        env:
          INPUT_JSON: ${{ github.event.inputs.input_json }}
        run: node login_detailed.js
