name: POB Daily Automation

on:
  schedule:
    - cron: '0 7 * * *'  # Every 15 minutes

jobs:
  run-pob-daily:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📦 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🧪 Install dependencies
        run: |
          npm install
          npx playwright install

      - name: 🚀 Run POB Daily Playwright Script
        run: |
          node automations/pob_automation.js