name: Run Secondary Sales Automation

on:
  workflow_dispatch:
    inputs:
      input_json:
        description: 'Input JSON string for Secondary Sales automation'
        required: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.checkout.outputs.commit }}
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v3

  setup-node:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

  install-deps:
    needs: setup-node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        id: cache-node
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Playwright browsers
        id: cache-browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers

      - name: Install dependencies and browsers
        run: |
          npm ci
          npx playwright install

  run-script:
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Restore Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers

      - name: Run secondary_sales.js
        env:
          INPUT_JSON: ${{ github.event.inputs.input_json }}
        run: node automations/secondary_sales.js
