name: Run Secondary Sales Automation

on:
  workflow_dispatch:
    inputs:
      input_json:
        description: 'Input JSON string for Secondary Sales automation'
        required: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      repo-path: ${{ steps.set-output.outputs.repo-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - id: set-output
        run: echo "repo-path=${{ github.workspace }}" >> $GITHUB_OUTPUT

  setup-node:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

  install-deps:
    needs: setup-node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Needed again to access repo contents
      - name: Install dependencies
        run: |
          npm install -D @playwright/test
          npm install
          npx playwright install
          npm install node-fetch


  run-script:
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Needed again for final run
      - name: Run secondary_sales.js
        env:
          INPUT_JSON: ${{ github.event.inputs.input_json }}
        run: node automations/secondary_sales.js
