name: Run Secondary Sales Automation

on:
  workflow_dispatch:
    inputs:
      input_json:
        description: 'Input JSON string for Secondary Sales automation'
        required: true

jobs:
  run-secondary-sales:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm install
          npx playwright install
      - name: Run secondary_sales.js
        env:
          INPUT_JSON: ${{ github.event.inputs.input_json }}
        run: node automations/secondary_sales.js
