name: 🧾 Doctor Service Automation

on:
  workflow_dispatch:
    inputs:
      months:
        description: 'Comma-separated months (e.g., Jun or Jan,Feb,Mar)'
        required: true
        default: 'Jun'
      year:
        description: 'Year (e.g., 2025)'
        required: true
        default: '2025'

jobs:
  run-dr-service:
    runs-on: ubuntu-latest

    env:
      AZURE_STORAGE_ACCOUNT: elbrit
      AZURE_STORAGE_KEY: ZEGJoULtZM+wqYf7Ls7IIhs3axdSSIp0ceZcHaRjKJeCugfTO7rz887WWm2zuAe3RVzRJ3XiXduK+AStdVeiBA==

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🎭 Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: 🧪 Set INPUT_JSON from Workflow Inputs
        run: |
          monthsArr=$(echo "${{ github.event.inputs.months }}" | awk -F',' '{ for(i=1;i<=NF;i++) printf "\"%s\",", $i }' | sed 's/,$//')
          echo "INPUT_JSON={\"months\":[${monthsArr}],\"year\":${{ github.event.inputs.year }}}" >> $GITHUB_ENV

      - name: 🚀 Run Dr Service Automation Script
        run: node automations/dr-service.js

      - name: 📤 Upload XLSX Reports (Artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dr-service-xlsx
          path: DRSERVICE_${{ github.event.inputs.year }}/
